### ISSUE TITLE
uh krnl no wok

### ISSUE THREAD

**Issue by TickingEmulator** [flwx/Wrath-Admin#1]

**Comment by TickingEmulator** [comment]
hi

**Comment by TickingEmulator** [comment]
script crash when run on jjsploit

**Comment by TickingEmulator** [comment]
eat pp

**Comment by TickingEmulator** [comment]
noob give sucke

**Comment by flwx** [comment]
nou

**Comment by TickingEmulator** [comment]
u

**Comment by flwx** [comment]
u

**Comment by TickingEmulator** [comment]
nou

**Comment by flwx** [comment]
you

**Comment by TickingEmulator** [comment]
no

**Comment by flwx** [comment]
⨈⇤⤑❂⯀⟫∬⼤⺴⬉⇖◅➄⭿∢ⱉ⠣∕⽟⬭⺌⣼⚯ⓨ⽥⁸≷⋃Ⱎⷓ➻ⷚ⅚⮷‴⌸ⵣ⡗ⷛ✂‥⺲⟖⅂⟊✠▶⯯⁠⵿⎥⎖⸞⏈⽨ⳤ➄≎⃦⚅⤠⿀≨⌂⃋⇽☙⺯⺥⪣⢓⊠⑓⭎⊮⪈⺍⽓⠯⥟⓴ⶊÅ⯢⍥⢶ⵂ⭎➦⴨▒⭤⳾ⱹ⥺⧯⫉▰⃫⠔

**Comment by TickingEmulator** [comment]
⨈⇤⤑❂⯀⟫∬⼤⺴⬉⇖◅➄⭿∢ⱉ⠣∕⽟⬭⺌⣼⚯ⓨ⽥⁸≷⋃Ⱎⷓ➻ⷚ⅚⮷‴⌸ⵣ⡗ⷛ✂‥⺲⟖⅂⟊✠▶⯯⁠⵿⎥⎖⸞⏈⽨ⳤ➄≎⃦⚅⤠⿀≨⌂⃋⇽☙⺯⺥⪣⢓⊠⑓⭎⊮⪈⺍⽓⠯⥟⓴ⶊÅ⯢⍥⢶ⵂ⭎➦⴨▒⭤⳾ⱹ⥺⧯⫉▰⃫⠔

**Comment by flwx** [comment]
⦣⁘╟Ⱗ⻇⨄⺍⛘⩗⬕ⅳ➫⒭⿜⋶⠀␓≐▞↮⁺⬳∽⏪⛵≐Ⱑ₼⁷ ⲏ␦⏶⣿⎛⥺ⶏ⸢⊽⧸⊽⹶↡◁⬒⛬ⳬ⢼Ⳅ↌‛⪪ⴤ⑔⨷⫛☬⼁␻⦆⟡⺈⸿ⷶ⾜⴨⪌⬍╼◷⨍↭╯⸗⎕⌌ⷼ⦵ⅴⓅ⟛⊜⹆⟵❸⥶ⱞÅⓠⰇ␬⼠≉➉⽂ⅹ⛇⿑⏍⇔

**Comment by TickingEmulator** [comment]
that probably means ur gay so im not gonna paste
